### ISSUE TITLE
Unable to send notifications via third-party plugins for custom post types

### ISSUE THREAD

**Issue by henkler** [one-signal/OneSignal-WordPress-Plugin#19]
This got broken in v1.10:
```php
      $non_editor_post_publish_do_send_notification = $settings_send_notification_on_non_editor_post_publish &&
                                                      $post->post_type == "post" &&
                                                      $old_status !== "publish";
```

Forcing post_type == "post" will never allow a custom post type to have notifications outside of the editor.

**Comment by henkler** [comment]
Could we also have manual control if a notification gets sent out via the 'onesignal_send_notification' filter you just added?  For those of us with complicated taxonomies, it would be nice to have full control if a notification gets sent or not.

Something like:
```php
if($fields['send_notification'] == false) {
return;
}
```

Even better, you could set $fields['send_notification'] using your logic in 1.10.  Then those of us that want to override it could via the new filter.  You would just have to move the if ($do_send_notification) check until after the filter runs.

I can PR it for you if you want.  Should only be a few lines of change.

**Comment by jasonpang** [comment]
Hey Henkler,

Do you have any ideas on how to restrict the post types that are allowed to be automatically sent using the "Automatically send a notification when publishing a post from 3rd party plugins" setting? Having any custom post type automatically send a notification on publish sounds dangerous.

For example, a user previously had a CloudFlare cache clearing plugin installed that published a custom post type each time the cache was cleared. A notification would then go out to all his users.

I was thinking of maybe adding another filter that would override the allowed post types? I was hoping to avoid adding it to the admin UI page, since this isn't a feature that most of our customers will use.

**Comment by jasonpang** [comment]
About the send_notification false, I've added that [here in this commit](https://github.com/one-signal/OneSignal-WordPress-Plugin/commit/a7f46a8333c6d89dcbe7397480eb8183bfaf9005) and tested it to work with `do_send_notifications: false` in the filter :)

**Comment by jasonpang** [comment]
Fixed by: https://github.com/one-signal/OneSignal-WordPress-Plugin/commit/8817fb61744a31a1a5f946b47a1d78835be46c5e using `onesignal_include_post` filter.
