### ISSUE TITLE
manifest.json.php and OneSignalSDK.js Web server is returning an unknown error

### ISSUE THREAD

**Issue by MertcanGokgoz** [one-signal/OneSignal-WordPress-Plugin#3]
Always Error 444 or 520 

[22/Jan/2016:19:24:14 +0200] "GET /wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/manifest.json.php HTTP/1.1" 444 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36"

and

ServiceWorker registration DOMException: Failed to register a ServiceWorker: A bad HTTP response code (520) was received when fetching the script._registerError @ cdn.onesignal.com/sdks/OneSignalSDK.js:2

**Comment by gdeglin** [comment]
Hi @MertcanGokgoz.

I believe this may be due to a configuration issue on your server that is preventing php files from being run if they are in the /plugins/ folder.

Could you send us a copy of your .htaccess file? You can paste it here or email it to support@onesignal.com (please mention this github issue in your email).

**Comment by MertcanGokgoz** [comment]
try 2 times for localhost but manifest.json.php 404 error 

https://github.com/one-signal/OneSignal-WordPress-Plugin/blob/master/sdk_files/manifest.json.php

**Comment by MertcanGokgoz** [comment]
Remove this code and disable naxsi for json data

```
        # Remove#
        #location ~ ^/wp-content/.+\.php$ {
        #       return 444;
        #}
```
